name: antvironment

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.8
  - pip
  - cudatoolkit
  - pytorch
  - pre-commit
  - black
  - isort
  - flake8
  - tensorboard
  - torchvision
  - pytorch-lightning
  - torchmetrics
  - matplotlib
  - ipython
  - libgcc
  - hydra-core
  - jupyterlab
  - scikit-learn
  - pandas
  - numpy
  - seaborn
  - python-dotenv
  - tqdm
  - pytorch-forecasting
  - pip
