# @package hydra.launcher
defaults:
  - submitit_slurm
  - _self_

timeout_min: 1440 # maximum time for the job in minutes
cpus_per_task: ${datamodule.num_workers} # kit nodes all have 72 cpus
tasks_per_node: 8 # == gpus_per_node
nodes: ${trainer.num_nodes}
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: haicore-gpu8
gres: gpu:8
signal_delay_s: 120
additional_parameters:
  {
    exclusive: true,
    signal: "SIGUSR1@200",
    contiguous: true,
  }
array_parallelism: 256
setup: [
    "conda activate hydra",
    "export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7",
    "export NCCL_NSOCKS_PERTHREAD=4", # number sockets opened by each helper CPU
    "export NCCL_SOCKET_NTHREADS=2",
  ] # number of CPUs per NCCL connection
max_num_timeout: 10
